// <auto-generated />
using HFSapi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HFSapi.Migrations
{
    [DbContext(typeof(HFSapiContext))]
    partial class HFSapiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HFSapi.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Fumbles");

                    b.Property<int>("Interceptions");

                    b.Property<int>("PassTDs");

                    b.Property<int>("PassYards");

                    b.Property<int>("PlayerId");

                    b.Property<int>("RecTDs");

                    b.Property<int>("RecYards");

                    b.Property<int>("Receptions");

                    b.Property<int>("RushTDs");

                    b.Property<int>("RushYards");

                    b.Property<int>("Season");

                    b.Property<string>("Team");

                    b.Property<int>("Week");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HFSapi.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvgPoints");

                    b.Property<int>("Games");

                    b.Property<string>("Name");

                    b.Property<string>("Position");

                    b.Property<int>("YearsPlayed");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
